import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import trpc from '@web/utils/trpc';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fetchUser = async () => {
    const user = await trpc.getUser.query({ id: '1' });
    console.log(user);
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
        <button onClick={fetchUser}>Fetch User</button>
      </body>
    </html>
  );
}
